language: python
python:
  - '2.7'
script: 
  - pip install PyExecJS
  - py.test -q HttpClient.py
  - py.test -q QLiker.py  
after_script:
  - nohup python QLiker.py >qbot.log&
  - sleep 500s
  - echo "still waiting"
  - sleep 500s
  - cat qbot.log
  - cat log.log
  - ls
  - killall python
